common: &common
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.11.1

version: 2
jobs:
  build-test:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-   # fallback
      - run: yarn install
      - run: yarn test
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  install-test:
    <<: *common
    steps:
      - checkout
      - run: yarn global add "https://github.com/$CIRCLE_USERNAME/$CIRCLE_PROJECT_REPONAME"
      - run: yarn test-global

workflows:
  version: 2
  build_and_install:
    jobs:
      - build-test
      - install-test
